const String _officialAlpha2Codes =
    'ADAEAFAGAIALAMAOAQARASATAUAWAXAZBABBBDBEBFBGBHBIBJBLBMBNBOBQBRBSBT'
    'BVBWBYBZCACCCDCFCGCHCICKCLCMCNCOCRCUCVCWCXCYCZDEDJDKDMDODZECEEEGEH'
    'ERESETFIFJFKFMFOFRGAGBGDGEGFGGGHGIGLGMGNGPGQGRGSGTGUGWGYHKHMHNHRHT'
    'HUIDIEILIMINIOIQIRISITJEJMJOJPKEKGKHKIKMKNKPKRKWKYKZLALBLCLILKLRLS'
    'LTLULVLYMAMCMDMEMFMGMHMKMLMMMNMOMPMQMRMSMTMUMVMWMXMYMZNANCNENFNGNI'
    'NLNONPNRNUNZOMPAPEPFPGPHPKPLPMPNPRPSPTPWPYQARERORSRURWSASBSCSDSESG'
    'SHSISJSKSLSMSNSOSRSSSTSVSXSYSZTCTDTFTGTHTJTKTLTMTNTOTRTTTVTWTZUAUG'
    'UMUSUYUZVAVCVEVGVIVNVUWFWSYEYTZAZMZW';

bool isOfficialAlpha2(String code) {
  if (code.length != 2) {
    return false;
  }
  for (var offset = 0; offset < _officialAlpha2Codes.length; offset += 2) {
    if (_officialAlpha2Codes.codeUnitAt(offset) == code.codeUnitAt(0) &&
        _officialAlpha2Codes.codeUnitAt(offset + 1) == code.codeUnitAt(1)) {
      return true;
    }
  }
  return false;
}
